#!/usr/bin/env bash 

case `uname` in
  Darwin )
    ifconfig $1 alias $2 netmask 255.255.255.252
    arp -s $3 fe:ff:ff:ff:ff:ff
    sleep 1
    route add $2/16 $3
    echo ifconfig $1 alias $2 netmask 255.255.255.252
    echo arp -s $3 fe:ff:ff:ff:ff:ff
    echo route add $2/16 $3
     ;;
  Linux )
    ip addr add $2/30 dev $1
    arp -s $3 fe:ff:ff:ff:ff:ff
    net=`echo $2 | cut -d . -f 1,2`.0.0
    route add -net $net/16 gw $3
    ;;
  esac
